name: Auto Update SportsTV

on:
  schedule:
    - cron: '*/20 * * * *' # Tự động chạy mỗi 20 phút
  workflow_dispatch: # Cho phép nhấn nút chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Cấp quyền cho Bot được phép ghi file vào kho của bạn
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        run: python bot.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add live.json
          git commit -m "Auto update links" || exit 0
          git push
